aivle/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    # path('delete/', views.delete, name='delete'),
]

aivle/board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    path('', views.main, name='main'),
    path('board/', views.boardpaging, name='board'),
    path('notice/', views.notice_boardpaging, name='notice'),
    path('write/',views.board_write, name = 'write'), # 게시글 작성
    path('detail/<int:pk>/',views.board_detail, name = 'board_detail'),
    path('mypage/', views.mypage, name='mypage'),
    path('withdraw/', views.withdraw, name='withdraw'),
    path('change_password/', views.change_password, name='change_password'),
    path('detail/download/<int:pk>',views.download, name="download"),
    # path('detail/<int:pk>/',views.boarddetail, name = 'board_detail'),
    # path('detail/<int:pk>/edit', views.boardedit, name = 'board_edit'),
    # path('detail/<int:pk>/delete',views.boarddelete,name='board_delete'),
    path('notice_detail/<int:pk>/',views.notice_detail, name = 'notice_detail'),
]

aivle/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('', include('board.urls'), name='board'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aivle/accounts/models.py
from django.db import models

# Create your models here.

aivle/accounts/forms.py
from dataclasses import fields
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

aivle/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth import get_user_model

# Create your views here.
@csrf_exempt
def register(request):
    if request.user.is_authenticated:
      return redirect('board:main')
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("accounts:login")
    else:
        form = RegisterForm()
    
    context = {'form' : form}
    return render(request, 'register.html', context)

aivle/accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
    />
    <title>NFT</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/styles.min_accounts.css' %}" />
  </head>
  <body>
    <!-- Start: Navigation Clean -->
    <nav class="navbar navbar-light navbar-expand-lg navigation-clean">
      <div class="container">
        <a class="navbar-brand" href="{% url 'board:main' %}">NFT 커뮤니티</a
        ><button
          data-bs-toggle="collapse"
          class="navbar-toggler"
          data-bs-target="#navcol-1"
        >
          <span class="visually-hidden">Toggle navigation</span
          ><span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navcol-1">
          <nav class="navbar navbar-light navbar-expand-md">
            <div class="container-fluid">
              <button
                data-bs-toggle="collapse"
                class="navbar-toggler"
                data-bs-target="#navcol-2"
              >
                <span class="visually-hidden">Toggle navigation</span
                ><span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navcol-2">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'board:notice' %}">공지사항</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'board:board' %}">게시판</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'board:mypage' %}">마이페이지</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
            </li>
              {% if user.is_authenticated %}
              <li class="nav-item"><a class="nav-link">{{user.username}}님</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">logout</a></li>
              {% else %}
              <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">login</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'accounts:register' %}">register</a></li>
              {% endif%}
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- End: Navigation Clean -->
    {% block content %}

    {% endblock %}
    <!-- Start: Footer Basic -->
    <footer class="footer-basic">
      <!-- Start: Social Icons -->
      <div class="social">
        <a href="#"><i class="icon ion-social-instagram"></i></a
        ><a href="#"><i class="icon ion-social-snapchat"></i></a
        ><a href="#"><i class="icon ion-social-twitter"></i></a
        ><a href="#"><i class="icon ion-social-facebook"></i></a>
      </div>
      <!-- End: Social Icons --><!-- Start: Links -->
      <ul class="list-inline">
        <li class="list-inline-item"><a href="#">Home</a></li>
        <li class="list-inline-item"><a href="#">Services</a></li>
        <li class="list-inline-item"><a href="#">About</a></li>
        <li class="list-inline-item"><a href="#">Terms</a></li>
        <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
      </ul>
      <!-- End: Links --><!-- Start: Copyright -->
      <p class="copyright">Company Name © 2022</p>
      <!-- End: Copyright -->
    </footer>
    <!-- End: Footer Basic -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

aivle/accounts/templates/login.html
{% extends "base.html"%} {% load static %} {% block content %}
<!-- Start: Login Form Clean -->
{% if request.user.is_authenticated %}
  <script>
    window.location.href = "{% url 'board:main' %}"
  </script>
{% endif %}
<section class="login-clean" style="display: flex; justify-content: center">
  <form method="post" style="max-width: 440px">
    {% csrf_token %} {% include "form_errors.html" %}
    <div class="illustration"><i class="icon ion-ios-navigate"></i></div>
    <div class="mb-3">
      <label class="form-label">아이디</label
      ><input
        class="form-control"
        type="text"
        name="username"
        id="username"
        placeholder="Username"
        value="{{ form.username.value | default_if_none:'' }}"
      />
    </div>
    <div class="mb-3">
      <label class="form-label">비밀번호</label
      ><input
        class="form-control"
        type="password"
        name="password"
        id="password"
        placeholder="Password"
        value="{{ form.password.value | default_if_none:'' }}"
      />
    </div>
    <div class="mb-3">
      <button class="btn btn-primary d-block w-100" type="submit">
        로그인
      </button>
    </div>
    <div>
      <a class="forgot" href="{% url 'accounts:register' %}"
        >계정이 없은신가요? 회원가입을 해보세요.</a
      >
    </div>
  </form>
</section>
<!-- End: Login Form Clean -->
{% endblock %}

aivle/accounts/templates/register.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- Start: Login Form Clean -->
    <section class="login-clean" style="display: flex; justify-content: center;">
      <form method="post" style="max-width: 440px">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="illustration"><i class="icon ion-ios-navigate"></i></div>
        <div class="mb-3">
          <label class="form-label">아이디</label
          ><input
            class="form-control"
            type="text"
            name="username"
            id="username"
            placeholder="Username"
            value="{{ form.username.value | default_if_none:'' }}"
          />
        </div>
        <div class="mb-3">
          <label class="form-label">이메일 주소</label
          ><input
            class="form-control"
            type="email"
            name="email"
            id="email"
            placeholder="Email"
            value="{{ form.email.value | default_if_none:'' }}"
          />
        </div>
        <div class="mb-3">
          <label class="form-label">비밀번호</label
          ><input
            class="form-control"
            type="password"
            name="password1"
            id="password1"
            placeholder="Password"
            value="{{ form.password1.value | default_if_none:'' }}"
          />
          <div>
            <ul style="font-size: 11px; padding-left: 12px; padding-top: 3px">
              <li>다른 개인 정보와 유사한 비밀번호는 사용할 수 없습니다.</li>
              <li>비밀번호는 최소 8자 이상이어야 합니다.</li>
              <li>숫자로만 이루어진 비밀번호는 사용할 수 없습니다.</li>
            </ul>
          </div>
        </div>
        <div class="mb-3">
          <label class="form-label">비밀번호 확인</label
          ><input
            class="form-control"
            type="password"
            name="password2"
            id="password2"
            placeholder="Confirm Password"
            value="{{ form.password2.value | default_if_none:'' }}"
          />
          <ul style="font-size: 10px; padding-left: 12px; padding-top: 3px">
            <li style="font-size: 11px">
              확인을 위해 이전과 동일한 비밀번호를 입력하세요.
            </li>
          </ul>
        </div>
        <div class="mb-3">
          <button class="btn btn-primary d-block w-100" type="submit">
            회원가입
          </button>
        </div>
        <a class="forgot" href="{% url 'accounts:login' %}">계정이 이미 있으신가요? 로그인 하러가기</a>
      </form>
    </section>
    <!-- End: Login Form Clean -->
  {% endblock %}