aivle/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    # path('delete/', views.delete, name='delete'),
]

aivle/board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    path('', views.main, name='main'),
    path('board/', views.boardpaging, name='board'),
    path('notice/', views.notice_boardpaging, name='notice'),
    path('write/',views.board_write, name = 'write'), # 게시글 작성
    path('detail/<int:pk>/',views.board_detail, name = 'board_detail'),
    path('mypage/', views.mypage, name='mypage'),
    path('withdraw/', views.withdraw, name='withdraw'),
    path('change_password/', views.change_password, name='change_password'),
    path('detail/download/<int:pk>',views.download, name="download"),
    # path('detail/<int:pk>/',views.boarddetail, name = 'board_detail'),
    # path('detail/<int:pk>/edit', views.boardedit, name = 'board_edit'),
    # path('detail/<int:pk>/delete',views.boarddelete,name='board_delete'),
    path('notice_detail/<int:pk>/',views.notice_detail, name = 'notice_detail'),
]

aivle/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('', include('board.urls'), name='board'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aivle/board/models.py
from django.db import models
from django.utils.timezone import now
from django.conf import settings
from django.contrib.auth.models import User


class Board(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=256, null=False)
    content = models.TextField(null=False)
    image = models.FileField(null = True, blank = True, upload_to='img/')
    date = models.DateTimeField(default=now, editable=False, null=False)
    # like = models.IntegerField(default=0, null=False)
    # dislike = models.IntegerField(default=0, null=False)
    hit_cnt = models.IntegerField(default=0, null=False)

    # def __str__(self):
    #     return self.title
    # # 제목이 board object가 되는 함수
    class Meta:
        db_table = 'board'




class Comment(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(default=now, editable=False, null=False)
    content = models.TextField()
    # like = models.IntegerField(default=0)
    # dislike = models.IntegerField(default=0)

    class Meta:
        db_table = 'comment'

# class File(models.Model):
#     file_idx = models.AutoField(primary_key=True)
#     board_id = models.ForeignKey(Board, on_delete=models.CASCADE)
#     user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name = "fleuser_id")
#     stored_file_name = models.CharField(max_length=45)
#     file_size = models.IntegerField()
#     create_date = models.DateTimeField(default=now, editable=False)

#     class Meta:
#         db_table = 'file'

class Notice(models.Model):
    title = models.CharField(max_length= 45)
    content = models.CharField(max_length= 400)
    date = models.DateTimeField(default=now, editable=False, null=False)
    username= models.CharField(max_length= 45, default="관리자")
    class Meta:
        db_table = 'notice'

aivle/board/forms.py
from django import forms
from .models import Board, Comment

class BoardWriteForm(forms.ModelForm):
    
    class Meta:
        model = Board
        fields = ('title','content', 'image',)




class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content']
        labels = {
        'content': '댓글내용',
        }

aivle/board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import BoardWriteForm, CommentForm
from .models import *
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator
import os
from config import settings
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.hashers import check_password
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm


def main(request):
    topics = Board.objects.all() 
    return render(request,'board/main.html',{'topics':topics})

@login_required
def mypage(request):
    now_page = request.GET.get('page', 1)
    user = request.user
    datas = Board.objects.filter(user_id = user).order_by('-id')

    paginator = Paginator(datas, 10)
    info = paginator.get_page(now_page)
    start_page = (int(now_page)-1) // 10 * 10 + 1
    end_page = start_page + 1

    if end_page > paginator.num_pages:
        end_page = paginator.num_pages

    context = {
        'info': info,
        'page_range': range(start_page, end_page + 1)
    }
    return render(request, 'board/mypage.html', context)


@csrf_exempt
@login_required
def withdraw(request):
    if request.method == 'POST':
        password = request.POST.get('password', '')
        user = request.user
        if check_password(password, user.password):
            user.delete()
            return redirect('board:main')

    return render(request, 'board/withdraw.html')


@csrf_exempt
@login_required
def board_write(request):
    if request.method == 'POST':
        form = BoardWriteForm(request.POST,request.FILES)
        if form.is_valid():
            writing = form.save(commit=False)
            writing.user = request.user
            writing.save()
            return redirect('board:board')
    else:
        form = BoardWriteForm()

    context = {'form': form}
    return render(request, 'board/write.html', context)


@csrf_exempt
def board_detail(request, pk):
    board = get_object_or_404(Board, pk=pk)
    comments = Comment.objects.filter(board = pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.board = board
            comment.author = request.user
            comment.save()
            return redirect('board:board_detail', pk)
    else:
        form = CommentForm()
    
    context = {
        'form' : form,
        'board': board,
        'comments':comments,
        'pk':pk
    }
    board.hit_cnt += 1
    board.save()

    return render(request, 'board/detail.html', context)



@csrf_exempt
def boardedit(request, pk):
    board = Board.objects.get(board_id=pk)
    if request.method == "POST":
        board.title = request.POST['title']
        board.content = request.POST['content']
        board.image = request.FILES['image']
        board.save()
        return redirect('board:board')
    else:
        boardForm = BoardWriteForm
        return render(request, 'board/update.html', {'boardForm': boardForm})


@csrf_exempt
@login_required
def boarddelete(request, pk):
    board = Board.objects.get(board_id=pk)
    board.delete()
    return redirect('board:board')


@csrf_exempt
def boardpaging(request) : #board 간략하게 paging
    now_page = request.GET.get('page',1)
    datas = Board.objects.order_by('-id')

    p = Paginator(datas, 10)
    info = p.get_page(now_page)
    start_page = (int(now_page) - 1) // 10 * 10 + 1
    end_page = start_page + 9
    if end_page > p.num_pages:
        end_page = p.num_pages
    context = {
        'info': info,
        'page_range': range(start_page, end_page + 1)
    }
    return render(request, 'board/board.html', context)

    
@csrf_exempt    
def notice_boardpaging(request):
    now_page = request.GET.get('page',1)
    datas =  Notice.objects.all().order_by('-id')

    p = Paginator(datas,10)
    info = p.get_page(now_page)
    start_page = (int(now_page) - 1) // 10 * 10 + 1
    end_page = start_page + 9
    if end_page > p.num_pages:
        end_page = p.num_pages
    context = {
        'info' : info,
        'page_range' : range(start_page, end_page + 1)
    }
    return render(request, 'board/notice.html', context) #notice.html => board에서 공지사항이라고만 수정하고 글쓰기 버튼 없앤 거 

@csrf_exempt
def notice_detail(request, pk):
    notice = get_object_or_404(Notice, pk=pk)
    context = {
        'notice': notice,
    }

    return render(request, 'board/notice_detail.html', context)


@csrf_exempt
def download(request, pk):
    board = get_object_or_404(Board, pk = pk)
    img = board.image
    imgPath = os.path.join(settings.MEDIA_ROOT, str(img))
    imgName = os.path.basename(imgPath)
    with open(imgPath, 'rb') as f:
        response = HttpResponse(
            f, content_type = 'application/octet-stream'
        )
        response['Content-Disposition'] = 'attachment; filename="{}"'.format(imgName)
    return response


@csrf_exempt
def comment(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.board = board
            comment.save()
            return redirect('board:detail', board_id=board_id)
    else:
        form = CommentForm()

    context = {'board': board, 'form': form}
    return render(request, 'board:detail', context)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('board:mypage')
    else:
        form = PasswordChangeForm(request.user)

    context = {
        'form': form,
    }

    return render(request, 'board/change_password.html', context)

aivle/board/templates/board/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
    />
    <title>NFT</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/styles.min_accounts.css' %}" />
  </head>
  <body>
    <!-- Start: Navigation Clean -->
    <nav class="navbar navbar-light navbar-expand-lg navigation-clean">
      <div class="container">
        <a class="navbar-brand" href="{% url 'board:main' %}">NFT 커뮤니티</a
        ><button
          data-bs-toggle="collapse"
          class="navbar-toggler"
          data-bs-target="#navcol-1"
        >
          <span class="visually-hidden">Toggle navigation</span
          ><span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navcol-1">
          <nav class="navbar navbar-light navbar-expand-md">
            <div class="container-fluid">
              <button
                data-bs-toggle="collapse"
                class="navbar-toggler"
                data-bs-target="#navcol-2"
              >
                <span class="visually-hidden">Toggle navigation</span
                ><span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navcol-2">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'board:notice' %}">공지사항</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'board:board' %}">게시판</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'board:mypage' %}">마이페이지</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
            </li>
              {% if user.is_authenticated %}
              <li class="nav-item"><a class="nav-link">{{user.username}}님</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">logout</a></li>
              {% else %}
              <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">login</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'accounts:register' %}">register</a></li>
              {% endif%}
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% block content %}

    {% endblock %}
    <!-- Start: Footer Basic -->
    <footer class="footer-basic", style="width: 100%;">
      <!-- Start: Social Icons -->
      <div class="social">
        <a href="#"><i class="icon ion-social-instagram"></i></a
        ><a href="#"><i class="icon ion-social-snapchat"></i></a
        ><a href="#"><i class="icon ion-social-twitter"></i></a
        ><a href="#"><i class="icon ion-social-facebook"></i></a>
      </div>
      <!-- End: Social Icons --><!-- Start: Links -->
      <ul class="list-inline">
        <li class="list-inline-item"><a href="#">Home</a></li>
        <li class="list-inline-item"><a href="#">Services</a></li>
        <li class="list-inline-item"><a href="#">About</a></li>
        <li class="list-inline-item"><a href="#">Terms</a></li>
        <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
      </ul>
      <!-- End: Links --><!-- Start: Copyright -->
      <p class="copyright">Company Name © 2022</p>
      <!-- End: Copyright -->
    </footer>
    <!-- End: Footer Basic -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

aivle/board/templates/board/board.html
{% extends "board/base.html" %} {% block content %}
<!-- End: Navigation Clean -->
<div class="container">
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>순번</th>
          <th>제목</th>
          <th>작성자</th>
          <th>조회수</th>
          <th>작성일</th>
        </tr>
      </thead>
      <tbody>
        {% for data in info %}
        <tr>
          <td>{{ data.id}}</td>
          <td><a href="../detail/{{ data.id}}">{{ data.title}}</a></td>
          <td>{{ data.user}}</td>
          <td>{{ data.hit_cnt}}</td>
          <td>{{ data.date}}</td>
        </tr>
        {% endfor%}
      </tbody>
    </table>
  </div>
  <nav
    class="d-sm-flex d-md-flex d-lg-flex justify-content-sm-center align-items-sm-center justify-content-md-center align-items-md-center justify-content-lg-center align-items-lg-center"
  >
    <ul class="pagination">
      <li class="page-item">
        <a class="page-link" href="#" aria-label="Previous"
          ><span aria-hidden="true">«</span></a
        >
      </li>
      {% for i in page_range %}
      <li class="page-item">
        <a class="page-link" href='{% url "board:board" %}?page={{ i }}'
          >{{ i }}</a
        >
      </li>
      {% endfor %}
      <li class="page-item">
        <a class="page-link" href="#" aria-label="Next"
          ><span aria-hidden="true">»</span></a
        >
      </li>
      <a href="{%url 'board:write' %}" class="btn btn-primary" type="button"
        >글쓰기</a
      >
    </ul>
  </nav>
</div>
{% endblock %}

aivle/board/templates/board/change_password.html
{% extends "board/base.html"%}
{%load static%}
{%block content%}
<link rel="stylesheet" href="{% static 'css/styles.css' %}" />
<div class="wrapper">
  <div class="sidebar">
    <h2>Mypage</h2>
    <ul>
      <li>
        <a href="{% url 'board:mypage' %}"
          ><i class="nav-link"></i>내가 쓴 글</a
        >
      </li>
      <li>
        <a href="{% url 'board:change_password' %}"
          ><i class="nav-link"></i>회원정보수정</a
        >
      </li>
      <li>
        <a href="{% url 'board:withdraw' %}"
          ><i class="nav-link"></i>회원탈퇴</a
        >
      </li>
      <li>
        <a href="/admin"
          ><i class="nav-link"></i>관리자페이지</a
        >
      </li>
    </ul>
  </div>
  <div class="main_content">
    <div class="container">
      <!-- Start: Login Form Clean -->
      <section
        class="login-clean"
        style="padding: 0px; padding-bottom: 80px; padding-top: 80px"
      >
        <form method="post" style="width: 400px; max-width: 440px">
          {% csrf_token %} {% include "form_errors.html" %} {{ form }}
          <div class="mb-3">
            <button
              class="btn btn-primary d-block w-100"
              type="submit"
              style="margin-right: 0px; margin-left: 0px"
            >
              비밀번호 수정
            </button>
          </div>
        </form>
      </section>
      <!-- End: Login Form Clean -->
    </div>
  </div>
</div>
{%endblock%}

aivle/board/templates/board/detail.html
{% extends "board/base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<!-- Start: Article Clean -->
<section class="article-clean">
  <div class="container">
    <div class="row">
      <div class="col-lg-10 col-xl-8 offset-lg-1 offset-xl-2">
        <!-- Start: Intro -->
        <div class="intro">
          <h1 class="text-center">{{ board.title }}</h1>
          <!-- Start: Date and Author -->
          <p class="text-center">
            <span class="by"> by {{ board.user }} </span>
            <span class="date"> {{ board.date }} </span>
            <span class="hit_cnt">조회수 : {{ board.hit_cnt }} </span>
          </p>
          <!-- End: Date and Author -->
          <div style="text-align: center">
            {% if board.image.url is not None %}
            <img src="{{board.image.url}}" />
            <br />
            <br />
            <a href="../download/{{pk}}" 
            class="btn btn-primary" 
            type="button">
            다운로드</a>
            {% endif %}
          </div>
        </div>
        <!-- End: Intro --><!-- Start: Text -->
        <div class="text">
          <br>
          <div style='text-align: center'> <p><b>게시글</p></b> </div>
          <hr />
          <div class="card my-3">
            <div class="card-body">
              <div class="card-text" style="white-space: pre-line">
                {{ board.content }}
              </div>
            </div>
          </div>
          <hr />
          <div style='text-align: center'> <p><b>댓글</p></b> </div>
          <hr />
          {% for comment in comments %}
          <div class="card my-3">
            <div class="card-body">
              <div class="card-text" style="white-space: pre-line">
                <span>작성자 : {{ comment.author }} </span>
                <span>내용 :  {{ comment.content }} </span>
                <span>작성일 : {{ comment.date }} </span>
              </div>
            </div>
          </div>
          {% endfor%}
          {% if user.is_authenticated %}
          <form method="POST" class="my-3">
            {% csrf_token %}
            {% include "form_errors.html" %}
            {% bootstrap_form form %}
            <input type="submit" value="댓글등록" class="btn btn-primary" />
          </form>
          {% endif %}
        </div>
        <!-- End: Text -->
      </div>
    </div>
  </div>
</section>
<!-- End: Article Clean -->
{% endblock %}

aivle/board/templates/board/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    
    {% for error in form.non_field_errors %}
    <!-- 넌필드 오류를 출력한다. -->
    <div class="alert alert-danger">
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
{% endif %}

aivle/board/templates/board/main.html
{% extends "board/base.html" %}
{% load static %}
{% block content %}
<!-- Start: Article Clean -->
    <section class="article-clean">
      <div class="container">
        <div class="row">
          <div class="col-lg-10 col-xl-8 offset-lg-1 offset-xl-2">
            <!-- Start: Intro -->
            <div class="intro", style = 'text-align:center;'>
              <h1 class="text-center"><strong>또 하나의 디지털 자산</strong></h1>
              <img
                class="img-fluid"
                src="{% static 'img/NFT.jpeg' %}"
              />
            </div>
            <!-- End: Intro --><!-- Start: Text -->
            <div class="text">
              <div style="text-align:center;">
                <p><b><i>NFT(Non-Fungible Token) 란?</i></b></p>
              </div>
              <div style="text-align:center;">
              <p>
                대체불가토큰을 의미하며, 블록체인 기술을 통한 "<span style = "text-decoration: underline">정품 인증서</span>"
                로서의 역할을 가집니다.<br>
                NFT가 적용된 디지털 코텐츠는 일반적으로 희소성을 가진 고유한 자산으로 인식되며<br>
                토큰을 통해 해당 작품의 소유권과 거래 이력을 확인 할 수 있습니다.<br>
              </p>
            </div>
            </div>
            <!-- End: Text -->
          </div>
        </div>
      </div>
    </section>
    <!-- End: Article Clean -->
  {% endblock %}

aivle/board/templates/board/mypage.html
{% extends "board/base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}" />
<div class="wrapper">
  <div class="sidebar">
    <h2>Mypage</h2>
    <ul>
      <li>
        <a href="{% url 'board:mypage' %}"><i class="nav-link"></i>내가 쓴 글</a>
      </li>
      <li>
        <a href="{% url 'board:change_password' %}"><i class="nav-link"></i>회원정보수정</a>
      </li>
      <li>
        <a href="{% url 'board:withdraw' %}"><i class="nav-link"></i>회원탈퇴</a>
      </li>
      <li>
        <a href="/admin"
          ><i class="nav-link"></i>관리자페이지</a
        >
      </li>
    </ul>
  </div>
  <div class="main_content">
    <div class="container">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>순번</th>
              <th>제목</th>
              <th>작성자</th>
              <th>조회수</th>
              <th>작성일</th>
            </tr>
          </thead>
          <tbody>
            {% for data in info %}
            <tr>
              <td>{{ data.id}}</td>
              <td><a href="../detail/{{ data.id}}">{{ data.title}}</a></td>
              <td>{{ data.user}}</td>
              <td>{{ data.hit_cnt}}</td>
              <td>{{ data.date}}</td>
            </tr>
            {% endfor%}
          </tbody>
        </table>
      </div>
      <nav
        class="d-sm-flex d-md-flex d-lg-flex justify-content-sm-center align-items-sm-center justify-content-md-center align-items-md-center justify-content-lg-center align-items-lg-center">
        <ul class="pagination">
          <li class="page-item">
            <a class="page-link" href="#" aria-label="Previous"><span aria-hidden="true">«</span></a>
          </li>
          {% for i in page_range %}
          <li class="page-item">
            <a class="page-link" href='{% url "board:board" %}?page={{ i }}'>{{ i }}</a>
          </li>
          {% endfor %}
          <li class="page-item">
            <a class="page-link" href="#" aria-label="Next"><span aria-hidden="true">»</span></a>
          </li>
          <a href="{%url 'board:write' %}" class="btn btn-primary" type="button"
        >글쓰기</a
      >
        </ul>
      </nav>
    </div>
  </div>
</div>
{% endblock %}

aivle/board/templates/board/notice.html
{% extends "board/base.html" %}
{% load static %}
{% block content %}
<!-- End: Navigation Clean -->
<div class="container">
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>순번</th>
          <th>제목</th>
          <th>작성자</th>
          <th>작성일</th>
        </tr>
      </thead>
      <tbody>
        {% for data in info %}
        <tr>
          <td>{{ data.id}}</td>
          <td><a href="../notice_detail/{{ data.id}}">{{ data.title}}</a></td>
          <td>{{ data.username}}</td>
          <td>{{ data.date}}</td>
        </tr>
        {% endfor%}
      </tbody>
    </table>
  </div>
  <nav
    class="d-sm-flex d-md-flex d-lg-flex justify-content-sm-center align-items-sm-center justify-content-md-center align-items-md-center justify-content-lg-center align-items-lg-center"
  >
    <ul class="pagination">
      <li class="page-item">
        <a class="page-link" href="#" aria-label="Previous"
          ><span aria-hidden="true">«</span></a
        >
      </li>
      {% for i in page_range %}
      <li class="page-item">
        <a class="page-link" href='{% url "board:notice" %}?page={{ i }}'
          >{{ i }}</a
        >
      </li>
      {% endfor %}
      <li class="page-item">
        <a class="page-link" href="#" aria-label="Next"
          ><span aria-hidden="true">»</span></a
        >
      </li>
    </ul>
  </nav>
</div>
{% endblock %}

aivle/board/templates/board/notice_detail.html
{% extends "board/base.html" %} 
{% load static %} 
{% block content %}
<!-- End: Navigation Clean --><!-- Start: Article Clean -->
<section class="article-clean">
  <div class="container">
    <div class="row">
      <div class="col-lg-10 col-xl-8 offset-lg-1 offset-xl-2">
        <!-- Start: Intro -->
        <div class="intro">
          <h1 class="text-center">{{ notice.title }}</h1>
          <!-- Start: Date and Author -->
          <p class="text-center">
            <span class="by"> by {{ notice.username }} </span>
            <span class="date"> {{ notice.date }} </span>
          </p>
          <!-- End: Date and Author -->
        </div>
        <!-- End: Intro --><!-- Start: Text -->
        <div class="text">
          <hr />
          <p>{{ notice.content }}</p>
          <hr />
        </div>
      </div>
      <!-- End: Text -->
    </div>
  </div>
</section>
{% endblock %}

aivle/board/templates/board/withdraw.html
{%extends "board/base.html"%} {%load static%} {%block content%}
<link rel="stylesheet" href="{% static 'css/styles.css' %}" />
<!-- End: Navigation Clean -->
<div class="wrapper" style="flex-wrap: wrap">
  <div class="sidebar">
    <h2>Mypage</h2>
    <ul>
      <li>
        <a href="{% url 'board:mypage' %}"
          ><i class="nav-link"></i>내가 쓴 글</a
        >
      </li>
      <li>
        <a href="{% url 'board:change_password' %}"
          ><i class="nav-link"></i>회원정보수정</a
        >
      </li>
      <li>
        <a href="{% url 'board:withdraw' %}"
          ><i class="nav-link"></i>회원탈퇴</a
        >
      </li>
      <li>
        <a href="/admin"
          ><i class="nav-link"></i>관리자페이지</a
        >
      </li>
    </ul>
  </div>
  <div class="main_content">
    <div class="container">
      <!-- Start: Login Form Clean -->
      <section
        class="login-clean"
        style="padding: 0px; padding-bottom: 80px; padding-top: 80px"
      >
        <form method="post" style="width: 440px; max-width: 440px">
          {% csrf_token %} {% include "form_errors.html" %}
          <h2 class="visually-hidden">Login Form</h2>
          <div class="illustration"><i class="icon ion-ios-navigate"></i></div>
          <div class="mb-3"></div>
          <p>안전한 회원탈퇴를 위해, 비밀번호를 확인해 주세요.</p>
          <ul>
            <li style="font-size: 11px">
              비밀번호 확인 후 아이디는 즉시 탈퇴됩니다.
            </li>
          </ul>
          <div class="mb-3">
            <input
              class="form-control"
              type="password"
              name="password"
              id="password"
              placeholder="Password"
              value="{{ form.username.value | default_if_none:'' }}"
            />
          </div>
          <div class="mb-3">
            <button
              class="btn btn-primary d-block w-100"
              type="submit"
              style="margin-right: 0px; margin-left: 0px"
            >
              회원탈퇴
            </button>
          </div>
        </form>
      </section>
      <!-- End: Login Form Clean -->
    </div>
  </div>
</div>
{%endblock%}

aivle/board/templates/board/write.html
{% extends "board/base.html" %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
<!-- End: Navigation Clean -->
<section style="padding: 0 50px">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %} {% include "form_errors.html" %} {% bootstrap_form form %}

    <button class="btn btn-primary" type="submit">저장</button>
    <a href= "{% url 'board:board' %}"> <button class="btn btn-primary" type="button">취소</button> </a>
  </form>
</section>
{% endblock%}